replicaCount: 1

image:
  repository: ghcr.io/gaurravvvv/gaurav_oraczen-devops-intern-assignment/notes-api
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

postgresql:
  primary:
    persistence:
      enabled: false
